version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "**/*"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directories: 
      - "**/*"
    schedule:
      interval: weekly
