[package]
name = "subxt-core-no-std-tests"
edition = "2021"
publish = false
version = "0.0.0"
resolver = "2"

[dependencies]
subxt-metadata = { path = "../../metadata", default-features = false }
subxt-core = { path = "../../core", default-features = false }
subxt-signer = { path = "../../signer", default-features = false, features = ["subxt"] }
subxt-macro = { path = "../../macro" }
codec = { package = "parity-scale-codec", version = "3.6.9", default-features = false, features = ["derive"] }
libc_alloc = { version = "1.0.6" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

# this shouldn't be needed, it's in workspace.exclude, but still
# I get the complaint unless I add it...
[workspace]
