[package]
name = "subxt-ffi"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
libc = "0.2.174"
once_cell = "1.21.3"
subxt = "0.42.1"
subxt-signer = "0.42.1"
tokio = { version = "1", features = ["full"] }

[lib]
crate-type = ["cdylib"]
name = "subxt_ffi"
