name: Build Substrate Binary

on:
  # Allow it to be manually ran to rebuild binary when needed:
  workflow_dispatch: {}
  # Run at 2am every day for nightly builds.
  schedule:
    - cron: "0 2 * * *"

jobs:
  tests:
    name: Build Substrate
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: checkout polkadot-sdk
        uses: actions/checkout@v4
        with:
          repository: paritytech/polkadot-sdk

      - name: Install dependencies
        run: sudo apt-get install -y protobuf-compiler

      - name: Install WASM toolchain
        run: rustup target add wasm32-unknown-unknown

      - name: Rust Cache
        uses: Swatinem/rust-cache@a95ba195448af2da9b00fb742d14ffaaf3c21f43 # v2.7.0

      - name: build substrate binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --manifest-path substrate/bin/node/cli/Cargo.toml

      - name: upload substrate binary
        uses: actions/upload-artifact@v3
        with:
          name: nightly-substrate-binary
          path: target/release/substrate-node
          retention-days: 2
          if-no-files-found: error